### PR TITLE
Firefox download

### LINKED ISSUE #52: Support for (standalone) browser download
There's currently possibility to download only PhantomJS as complete browser. There're portable packages of Firefox and Google Chrome available, which could be used same way as PhantomJS in testing and same time be sure that there's no version incompatibility with Selenium.

New drivers could be at least:
- firefox (environment property pointing to firefox binary: webdriver.firefox.bin)
- googlechrome

### PR DESCRIPTION
**Pull request by Hi-Fi**
+ Fixes #52

### CODE REVIEW

**Comment by Hi-Fi** [comment]
Deployment to Sonatype seems to be broken
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project driver-binary-downloader-maven-plugin: Failed to deploy artifacts: Could not transfer artifact com.lazerycode.selenium:driver-binary-downloader-maven-plugin:jar:DEV-20170808.160728-19 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/lazerycode/selenium/driver-binary-downloader-maven-plugin/DEV-SNAPSHOT/driver-binary-downloader-maven-plugin-DEV-20170808.160728-19.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

**Comment by Hi-Fi** [comment]
Linux version requires some checks, too, so checking those same time as formatting.

**Comment by Hi-Fi** [comment]
Linux version working, and format (mostly) same as original one.

**Comment by Hi-Fi** [comment]
Any issues with this? There's quite a lot of logging when downloading full browsers, but i think it might be also OK as that extraction information is just information.

**Comment by Ardesco** [comment]
Looks ok, however the filerepository.xml  has not been updated

**Comment by Hi-Fi** [comment]
I'll fix that later today. For Linux it's easy (as Firefox is distributed as tarball), but for Windows and Mac I have to probably check some portable Firefox download location.

**Comment by Hi-Fi** [comment]
Would this be now merge- and releaseable?

**Pull request merged**
